#!/usr/bin/env python

import json
import os
import sys

import git

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
import backend

webapp_git_repo = git.Repo(os.path.join(backend.BACKEND_BASE_PATH, '..'))
with open(backend.BACKEND_CONFIG_PATH) as f:
    config = json.load(f)
    simulator_git_repo = git.Repo(
        os.path.join(
            os.path.dirname(backend.BACKEND_CONFIG_PATH),
            config['simulator_path']
        )
    )

ret = {}
for repo in [webapp_git_repo, simulator_git_repo]:
    info = {}
    info['repo'] = os.path.dirname(repo.git_dir)

    try:
        info['branch'] = webapp_git_repo.active_branch.name
    except TypeError:
        info['branch'] = 'unknown'

    info['short_hash'] = repo.head.object.hexsha[:7]

    if repo == webapp_git_repo:
        ret['webapp'] = info
    elif repo == simulator_git_repo:
        ret['simulator'] = info
    else:
        raise NotImplementedError()

print json.dumps(ret)
