#!/usr/bin/env python

# add the parent directory of this file to Python module search path
# so that backend.utils can be imported
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

# start the backend server
import backend.utils
backend.utils.start_server()
